#!/usr/bin/env Rscript
# vim: set syntax=r:

args <- commandArgs(trailingOnly=TRUE)
if (length(args) == 0) {
  stop("Please specify tool directory (@tool) on launch.")
}
swirl::install_course_directory(paste0(args[1], "/src/Cats_Teach_Stats"))