all: install_swirl_course

install: install_swirl_course
		install --mode 0755 -D install_swirl_course ../bin/install_swirl_course
		
clean:

distclean: clean
		rm -f ../bin/install_swirl_course

.PHONY: all install clean distclean